
import { useState } from "react";
import "../../styles/landing_page/faqSections.css";

const faqs = [
  {
    question: "What is MemeLend?",
    answer:
      "MemeLend is a decentralized platform where anyone can launch a token with built-in liquidity and lending mechanics. Users can long, short, and earn yield on meme tokens — all on-chain.",
  },
  {
    question: "How does token creation work?",
    answer:
      "When a token is launched on MemeLend, the supply is automatically split between a liquidity vault and a lending vault. Liquidity powers trading, while the lending vault enables short positions and generates yield for holders.",
  },
  {
    question: "What is the bonding curve?",
    answer:
      "The creator adds WSOL to bond with the token liquidity, creating a fair bonding curve. As trading volume increases, the price adjusts automatically based on supply and demand.",
  },
  {
    question: "Why is the lending vault locked?",
    answer:
      "To prevent creators from rug-pulling liquidity. The lending vault unlocks gradually over 7 days, then 30 days, and the remaining tokens after 180 days — protecting early buyers and maintaining trading depth.",
  },
  {
    question: "How does shorting work?",
    answer:
      "Shorting borrows tokens from the lending vault. Traders bet on price movements by borrowing high and buying back lower — all backed by the protocol’s smart accounting.",
  },
  {
    question: "Can I earn rewards by staking?",
    answer:
      "Yes! Users can stake their tokens into the lending vault to earn a share of trading fees and yield generated by short sellers.",
  },
  {
    question: "How does the presale option work?",
    answer:
      "If a creator doesn’t have liquidity to start, they can run a presale. Presale buyers help fund initial liquidity and earn a share of creator fees as long as they hold their presale tokens.",
  },
  {
    question: "What fees are involved?",
    answer:
      "Small fees apply to each trade and are distributed between the creator, platform, referrers, and yield.",
  },
  {
    question: "Is MemeLend secure?",
    answer:
      "Yes — MemeLend is built on Solana using audited smart contracts. You stay in full control of your wallet and assets.",
  },
  {
    question: "Do you support referrals?",
    answer:
        "Yes! Traders can earn ongoing referral rewards when users they refer trade on MemeLend. Referral earnings are claimable anytime.",
    },
    {
    question: "What do I need to start?",
    answer:
        "Just a Solana wallet (like Phantom or Backpack) and some SOL for gas. Connect your wallet and you're ready to launch or trade tokens.",
    },
];


function FAQSection() {
    const [openIndex, setOpenIndex] = useState<number | null>(null);

    const toggleFAQ = (index: number) => {
        setOpenIndex(openIndex === index ? null : index);
    };

  return (
    <div className="faq-section">
      <div className="faq-header">
        <h1>Frequently Asked Questions</h1>
      </div>
      <div className="faq-container">
        {faqs.map((faq, index) => (
          <div
            className={`faq-item ${openIndex === index ? "open" : ""}`}
            key={index}
          >
            <div className="faq-summary" onClick={() => toggleFAQ(index)}>
              <p>{faq.question}</p>
              <span className="faq-icon">{openIndex === index ? "-" : "+"}</span>
            </div>
            {openIndex === index && (
              <div className="faq-answer">
                <p>{faq.answer}</p>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}

export default FAQSection