-- AlterTable
ALTER TABLE "Candlestick" ADD COLUMN     "closeUsd" DOUBLE PRECISION,
ADD COLUMN     "highUsd" DOUBLE PRECISION,
ADD COLUMN     "lowUsd" DOUBLE PRECISION,
ADD COLUMN     "openUsd" DOUBLE PRECISION;
